import type { Job } from "@/types/job"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Construction Labourer",
    company: "BuildCorp Ltd",
    location: "Toronto, ON",
    payMin: 22,
    payMax: 28,
    payType: "hourly",
    duration: "medium",
    jobType: "general-labour",
    shift: ["day"],
    workType: "full-time",
    experienceLevel: "entry",
    postedDate: "2024-01-15",
    startDate: "2024-02-01",
    description:
      "We are seeking reliable construction labourers to join our team for a major commercial project. You will assist with various construction tasks including material handling, site cleanup, and supporting skilled tradespeople.",
    requirements: [
      "Physical fitness and ability to lift 50+ lbs",
      "Reliable transportation",
      "Safety-conscious attitude",
      "Ability to work in all weather conditions",
    ],
    skills: ["Construction Safety", "Material Handling", "Basic Tools"],
    certificates: ["Construction Safety Training"],
    benefits: {
      accommodation: false,
      meals: true,
      transport: false,
    },
    company_profile: {
      description:
        "BuildCorp Ltd is a leading construction company with over 20 years of experience in commercial and residential projects.",
      rating: 4.2,
      activeJobs: 8,
    },
    practical_info: {
      workingHours: "7:00 AM - 4:00 PM",
      paymentFrequency: "weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "2",
    title: "Warehouse Forklift Operator",
    company: "LogiFlow Solutions",
    location: "Mississauga, ON",
    payMin: 25,
    payMax: 30,
    payType: "hourly",
    duration: "permanent",
    jobType: "operator",
    shift: ["day", "night"],
    workType: "full-time",
    experienceLevel: "intermediate",
    postedDate: "2024-01-14",
    startDate: "2024-01-22",
    description:
      "Join our warehouse team as a certified forklift operator. You will be responsible for loading, unloading, and moving materials throughout our distribution center.",
    requirements: [
      "Valid forklift certification",
      "2+ years warehouse experience",
      "Attention to detail",
      "Ability to work rotating shifts",
    ],
    skills: ["Forklift Operation", "Warehouse Management", "Inventory Control"],
    certificates: ["Forklift Certification", "WHMIS"],
    benefits: {
      accommodation: false,
      meals: false,
      transport: true,
    },
    company_profile: {
      description:
        "LogiFlow Solutions is a premier logistics company serving the GTA with state-of-the-art warehouse facilities.",
      rating: 4.5,
      activeJobs: 12,
    },
    practical_info: {
      workingHours: "Rotating shifts: 6AM-2PM / 2PM-10PM / 10PM-6AM",
      paymentFrequency: "bi-weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "3",
    title: "Electrical Apprentice",
    company: "PowerTech Electric",
    location: "Ottawa, ON",
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    duration: "long-term",
    jobType: "skilled-trade",
    shift: ["day"],
    workType: "full-time",
    experienceLevel: "entry",
    postedDate: "2024-01-13",
    startDate: "2024-02-05",
    description:
      "Excellent opportunity for an electrical apprentice to learn from experienced electricians while working on residential and commercial projects.",
    requirements: [
      "Enrolled in electrical apprenticeship program",
      "Basic understanding of electrical systems",
      "Valid driver's license",
      "Willingness to learn and follow safety protocols",
    ],
    skills: ["Basic Electrical", "Hand Tools", "Safety Protocols"],
    certificates: ["First Aid/CPR"],
    benefits: {
      accommodation: true,
      meals: true,
      transport: false,
    },
    company_profile: {
      description: "PowerTech Electric has been providing quality electrical services across Ottawa for over 15 years.",
      rating: 4.7,
      activeJobs: 5,
    },
    practical_info: {
      workingHours: "7:30 AM - 4:30 PM",
      paymentFrequency: "weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "4",
    title: "Site Supervisor",
    company: "MegaBuild Construction",
    location: "Calgary, AB",
    payMin: 35,
    payMax: 45,
    payType: "hourly",
    duration: "permanent",
    jobType: "supervisor",
    shift: ["day"],
    workType: "full-time",
    experienceLevel: "expert",
    postedDate: "2024-01-12",
    startDate: "2024-01-29",
    description:
      "Lead construction teams on major infrastructure projects. Responsible for coordinating work activities, ensuring safety compliance, and maintaining project schedules.",
    requirements: [
      "5+ years construction supervision experience",
      "Strong leadership and communication skills",
      "Knowledge of construction safety regulations",
      "Project management experience",
    ],
    skills: ["Project Management", "Team Leadership", "Safety Management", "Quality Control"],
    certificates: ["Construction Safety Officer", "Project Management"],
    benefits: {
      accommodation: true,
      meals: true,
      transport: true,
    },
    company_profile: {
      description: "MegaBuild Construction is a major player in infrastructure development across Western Canada.",
      rating: 4.3,
      activeJobs: 15,
    },
    practical_info: {
      workingHours: "6:00 AM - 5:00 PM",
      paymentFrequency: "bi-weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "5",
    title: "Mason / Bricklayer",
    company: "StoneCraft Builders",
    location: "Edmonton, AB",
    payMin: 30,
    payMax: 36,
    payType: "hourly",
    duration: "long-term",
    jobType: "skilled-trade",
    shift: ["day"],
    workType: "full-time",
    experienceLevel: "intermediate",
    postedDate: "2024-01-11",
    startDate: "2024-02-10",
    description:
      "We are looking for experienced masons/bricklayers for commercial and residential projects. Duties include laying bricks, blocks, and stone with precision.",
    requirements: [
      "3+ years masonry experience",
      "Ability to read blueprints",
      "Knowledge of mortar mixing",
      "Physical strength for heavy lifting",
    ],
    skills: ["Masonry", "Blueprint Reading", "Scaffolding"],
    certificates: ["Fall Protection", "Safety Training"],
    benefits: {
      accommodation: false,
      meals: true,
      transport: false,
    },
    company_profile: {
      description: "StoneCraft Builders specializes in quality masonry and stonework across Alberta.",
      rating: 4.1,
      activeJobs: 6,
    },
    practical_info: {
      workingHours: "7:00 AM - 5:00 PM",
      paymentFrequency: "weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "6",
    title: "Heavy Equipment Operator",
    company: "NorthStar Infrastructure",
    location: "Winnipeg, MB",
    payMin: 32,
    payMax: 40,
    payType: "hourly",
    duration: "medium",
    jobType: "operator",
    shift: ["day"],
    workType: "full-time",
    experienceLevel: "intermediate",
    postedDate: "2024-01-10",
    startDate: "2024-01-25",
    description:
      "Operate excavators and bulldozers for a large-scale road construction project. Ensure safe and efficient operation of machinery.",
    requirements: [
      "Valid heavy equipment license",
      "3+ years operating experience",
      "Safety-conscious",
      "Ability to work in outdoor conditions",
    ],
    skills: ["Excavator Operation", "Bulldozer Operation", "Site Safety"],
    certificates: ["Heavy Equipment License", "First Aid"],
    benefits: {
      accommodation: true,
      meals: false,
      transport: true,
    },
    company_profile: {
      description: "NorthStar Infrastructure builds and maintains critical infrastructure projects across Manitoba.",
      rating: 4.4,
      activeJobs: 10,
    },
    practical_info: {
      workingHours: "6:30 AM - 4:00 PM",
      paymentFrequency: "bi-weekly",
      paymentMethod: "bank-transfer",
    },
  },
  {
    id: "7",
    title: "Painter / Finisher",
    company: "ProFinish Contractors",
    location: "Vancouver, BC",
    payMin: 20,
    payMax: 28,
    payType: "hourly",
    duration: "short-term",
    jobType: "skilled-trade",
    shift: ["day"],
    workType: "contract",
    experienceLevel: "entry",
    postedDate: "2024-01-09",
    startDate: "2024-01-20",
    description:
      "Looking for painters/finishers for a short-term renovation project. Tasks include wall preparation, painting, and finishing details.",
    requirements: [
      "Basic painting skills",
      "Attention to detail",
      "Ability to work independently",
      "Good communication",
    ],
    skills: ["Painting", "Surface Prep", "Finishing"],
    certificates: [],
    benefits: {
      accommodation: false,
      meals: false,
      transport: false,
    },
    company_profile: {
      description: "ProFinish Contractors deliver high-quality finishing work for residential and commercial clients.",
      rating: 4.0,
      activeJobs: 4,
    },
    practical_info: {
      workingHours: "8:00 AM - 4:00 PM",
      paymentFrequency: "weekly",
      paymentMethod: "cash",
    },
  },
  {
    id: "8",
    title: "Welder",
    company: "SteelWorks Fabrication",
    location: "Hamilton, ON",
    payMin: 28,
    payMax: 35,
    payType: "hourly",
    duration: "long-term",
    jobType: "skilled-trade",
    shift: ["day", "night"],
    workType: "full-time",
    experienceLevel: "expert",
    postedDate: "2024-01-08",
    startDate: "2024-01-27",
    description:
      "Experienced welder needed for structural steel fabrication. Must be proficient in MIG and TIG welding techniques.",
    requirements: [
      "Welding certification",
      "4+ years welding experience",
      "Ability to read technical drawings",
      "Safety-first mindset",
    ],
    skills: ["MIG Welding", "TIG Welding", "Blueprint Reading"],
    certificates: ["CWB Welding Certification"],
    benefits: {
      accommodation: true,
      meals: true,
      transport: true,
    },
    company_profile: {
      description: "SteelWorks Fabrication provides custom steel structures for industrial and commercial projects.",
      rating: 4.6,
      activeJobs: 9,
    },
    practical_info: {
      workingHours: "Shifts: 6AM-2PM / 2PM-10PM",
      paymentFrequency: "bi-weekly",
      paymentMethod: "bank-transfer",
    },
  }
]
